### ISSUE TITLE
Fatal Exception: java.lang.InternalError

### ISSUE THREAD

**Issue by Armen101** [mopub/mopub-android-sdk#364] opened 2019-11-18 08:00 UTC
java.lang.Thread.nativeCreate (Thread.java)
java.lang.Thread.start + 733 (Thread.java:733)
com.moat.analytics.mobile.mpub.w.a + 24 (w.java:24)
com.moat.analytics.mobile.mpub.w.b (w.java)
com.moat.analytics.mobile.mpub.w$a.a + 100 (w.java:100)
com.moat.analytics.mobile.mpub.w$a.run (w.java)
android.os.Handler.handleCallback + 790 (Handler.java:790)
android.os.Looper.loop + 164 (Looper.java:164)
com.moat.analytics.mobile.mpub.w$1.run + 30 (w.java:30)

Ad Formats - Banner, Interstitial, Rewarded Video
MoPub SDK Version - 5.10.0

**Comment by hmertkahraman** [comment] 2019-11-18 17:55
Hi @Armen101 ,

Thanks for reporting this. 

For us to understand and troubleshoot this issue, in addition to the information you already shared, can you also please share exact reproduction steps, and the stack trace of the crash? If the reproduction steps include requesting ads, can you also share the ad unit ID that was used?

Thanks,
MoPub Team

**Comment by Armen101** [comment] 2019-11-19 13:29
Hi @hmertkahraman , thanks for your reply. Unfortunately, I can't give you more information because I have gotten this from Crash tracking tools

**Comment by Armen101** [comment] 2019-11-19 13:43
@hmertkahraman I replyed you [issuews-42](https://github.com/mopub/mopub-unity-mediation/issues/42)

**Comment by Armen101** [comment] 2019-11-19 13:54
`#0. Crashed: Thread-62
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start + 733(Thread.java:733)
       at com.moat.analytics.mobile.mpub.w.a + 24(w.java:24)
       at com.moat.analytics.mobile.mpub.w.b(w.java)
       at com.moat.analytics.mobile.mpub.w$a.a + 100(w.java:100)
       at com.moat.analytics.mobile.mpub.w$a.run(w.java)
       at android.os.Handler.handleCallback + 790(Handler.java:790)
       at android.os.Handler.dispatchMessage + 99(Handler.java:99)
       at android.os.Looper.loop + 164(Looper.java:164)
       at com.moat.analytics.mobile.mpub.w$1.run + 30(w.java:30)

--

Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start + 733(Thread.java:733)
       at com.moat.analytics.mobile.mpub.w.a + 24(w.java:24)
       at com.moat.analytics.mobile.mpub.w.b(w.java)
       at com.moat.analytics.mobile.mpub.w$a.a + 100(w.java:100)
       at com.moat.analytics.mobile.mpub.w$a.run(w.java)
       at android.os.Handler.handleCallback + 790(Handler.java:790)
       at android.os.Handler.dispatchMessage + 99(Handler.java:99)
       at android.os.Looper.loop + 164(Looper.java:164)
       at com.moat.analytics.mobile.mpub.w$1.run + 30(w.java:30)

#0. Crashed: Thread-62
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start + 733(Thread.java:733)
       at com.moat.analytics.mobile.mpub.w.a + 24(w.java:24)
       at com.moat.analytics.mobile.mpub.w.b(w.java)
       at com.moat.analytics.mobile.mpub.w$a.a + 100(w.java:100)
       at com.moat.analytics.mobile.mpub.w$a.run(w.java)
       at android.os.Handler.handleCallback + 790(Handler.java:790)
       at android.os.Handler.dispatchMessage + 99(Handler.java:99)
       at android.os.Looper.loop + 164(Looper.java:164)
       at com.moat.analytics.mobile.mpub.w$1.run + 30(w.java:30)

#1. pool-85-thread-1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$ + 2137(Thread.java:2137)
       at sun.misc.Unsafe.park + 358(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.park + 190(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await + 2059(AbstractQueuedSynchronizer.java:2059)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take + 1120(ScheduledThreadPoolExecutor.java:1120)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take + 1113(ScheduledThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor.getTask + 1087(ThreadPoolExecutor.java:1087)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1147(ThreadPoolExecutor.java:1147)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 636(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run + 764(Thread.java:764)
`

**Comment by rsatrasala** [comment] 2019-12-20 23:36
Closing due to lack of reproduction steps. Please reopen a new issue if needed

**Closed by rsatrasala** 2019-12-20 23:36 UTC
