### ISSUE TITLE
Is it possible to use facebook native and facebook native banner in one app?

### ISSUE THREAD

**Issue by geraldika** [mopub/mopub-android-sdk#449] opened 2020-12-17 10:22 UTC
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by chauduyphanvu** [comment] 2020-12-17 15:29
Duplicate of https://github.com/mopub/mopub-android-mediation/issues/317.

**Closed by chauduyphanvu** 2020-12-17 15:29 UTC
