### ISSUE TITLE
IllegalStateException in AdViewController

### ISSUE THREAD

**Issue by do-current** [mopub/mopub-android-sdk#379] opened 2020-03-04 12:12 UTC
I'm getting the crash reports in Crashlytics.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.7.1
#### Android Studio Version:
3.6
#### Gradle Version:
3.5.3
#### Device model and OS Version:
![image](https://user-images.githubusercontent.com/56651169/75878013-74998e00-5e4b-11ea-93ba-00d0b042f588.png)

#### Steps to reproduce the behavior:
Can't reproduce

#### Expected behavior:
App doesn't crash

#### Observed behavior:
App crashes

#### Evidence:
```
Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner + 4976(ViewGroup.java:4976)
       at android.view.ViewGroup.addView + 4807(ViewGroup.java:4807)
       at android.view.ViewGroup.addView + 4779(ViewGroup.java:4779)
       at com.mopub.mobileads.AdViewController$3.run + 643(AdViewController.java:643)
       at android.os.Handler.handleCallback + 808(Handler.java:808)
       at android.os.Handler.dispatchMessage + 101(Handler.java:101)
       at android.os.Looper.loop + 166(Looper.java:166)
       at android.app.ActivityThread.main + 7529(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run + 245(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main + 921(ZygoteInit.java:921)
```

After checking the codebase of MoPub SDK, I think the root cause is the `view` still has the parent when adding to `moPubView`. We need check and remove it from its parent first.

```
    void setAdContentView(final View view) {
        // XXX: This method is called from the WebViewClient's callbacks, which has caused an error on a small portion of devices
        // We suspect that the code below may somehow be running on the wrong UI Thread in the rare case.
        // see: https://stackoverflow.com/questions/10426120/android-got-calledfromwrongthreadexception-in-onpostexecute-how-could-it-be
        mHandler.post(new Runnable() {
            @Override
            public void run() {
                MoPubView moPubView = getMoPubView();
                if (moPubView == null) {
                    return;
                }
                moPubView.removeAllViews();
                moPubView.addView(view, getAdLayoutParams(view));
            }
        });
    }
```

**Comment by chauduyphanvu** [comment] 2020-03-04 15:28
@do-current, this is a duplicate of https://github.com/mopub/mopub-android-sdk/issues/345. See my response [here](https://github.com/mopub/mopub-android-sdk/issues/345#issuecomment-541694515) for where we left off. Thanks!

Vu Chau
MoPub Team

**Comment by do-current** [comment] 2020-03-04 16:41
Hi @chauduyphanvu , yes I had seen before I opened this issue. I have a question related to your answer:

> However, see that there is a moPubView.removeAllViews() call right below, which should remove all the existing children Views.

What happen if the `view`'s parent is not `moPubView`?

**Comment by chauduyphanvu** [comment] 2020-03-04 19:43
@do-current, I'm not seeing a scenario where that could happen, because our code doesn't add a parent to this `view` anywhere (it has child views throughout the lifecycle of the ad, just not a parent). 

> What happen if the view's parent is not moPubView?

Since we can't reproduce this crash, are you able to assist by helping us validate that?

**Comment by do-current** [comment] 2020-03-05 09:45
@chauduyphanvu, unfortunately, I'm unable to reproduce this issue. I also checked the MoPub SDK code but still have no idea. However, can you consider the following code as a workaround for this issue?

```
moPubView.removeAllViews();              
if (view.getParent() != null) {
     ((ViewGroup) view.getParent()).removeView(view);
}
moPubView.addView(view, getAdLayoutParams(view));
```

**Comment by chauduyphanvu** [comment] 2020-03-05 15:27
@do-current, that looks reasonable but let me relay it to the rest of the team. We'll check what can be done. Thanks!

**Comment by do-current** [comment] 2020-03-23 20:34
@chauduyphanvu Hi. Is they any updates regarding this?

**Comment by chauduyphanvu** [comment] 2020-03-24 16:57
@do-current, thanks for checking. There currently is no update yet. Stay tuned - we'll update this thread accordingly!

**Comment by do-current** [comment] 2020-06-25 18:30
@chauduyphanvu Hi Duy. May I ask if there is any updates on this?

**Comment by chauduyphanvu** [comment] 2020-06-26 18:29
@do-current, are you still seeing this crash? We don't have an update on a potential fix since we also can't reproduce it. 

If this crash continues to happen to your app but in production, would you mind sharing a stripped down version of the app with us (you may privately share it with support@mopub.com and mention this GitHub Issue) so we can investigate? Thanks!

**Comment by damian-burke** [comment] 2020-08-17 07:00
Just to chime in: This is currently the top crash in our application.

Stacktrace:
```
Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5099)
       at android.view.ViewGroup.addView(ViewGroup.java:4930)
       at android.view.ViewGroup.addView(ViewGroup.java:4902)
       at com.mopub.mobileads.AdViewController$3.run(AdViewController.java:651)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

MoPub Version: 5.12.0

Unfortunately I also cannot reproduce this issue locally. It seems like an edge-case happening for certain users. 
Our crash reporting tells me that it's distributed across all Android versions, not specific to any vendors.

**Comment by chauduyphanvu** [comment] 2020-10-21 20:54
Closing as there has been no repro case.

**Closed by chauduyphanvu** 2020-10-21 20:54 UTC
Labels: bug, duplicate
