### ISSUE TITLE
 com.mopub.mobileads.MoPubFullscreen.lambda$preRender$0$MoPubFullscreen

### ISSUE THREAD

**Issue by prdpcrank** [mopub/mopub-android-sdk#414] opened 2020-07-27 08:26 UTC
One line summary of the issue here

- [ X] I am submitting a bug report for existing functionality
- [X ] I visited https://developers.mopub.com/ and found no answer
- [X ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ X] I checked to make sure that this issue has not already been filed

#### Device model and OS Version:
![Screen Shot 2020-07-27 at 1 53 05 PM](https://user-images.githubusercontent.com/14123919/88519983-97059100-d010-11ea-89dc-89c19831579f.png)

![Screen Shot 2020-07-27 at 1 53 15 PM](https://user-images.githubusercontent.com/14123919/88519988-9967eb00-d010-11ea-9f94-d3a541f6775d.png)

#### Observed behavior:
Crashing.

#### Evidence:
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mopub.mobileads.AdLifecycleListener$InteractionListener.onAdFailed(com.mopub.mobileads.MoPubErrorCode)' on a null object reference
       at com.mopub.mobileads.MoPubFullscreen.lambda$preRender$0$MoPubFullscreen(MoPubFullscreen.java:182)
       at com.mopub.mobileads.-$$Lambda$MoPubFullscreen$3H3zkNFnaPQ4PqCgAa8VbWGmgJs.run(:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

**Comment by p158276** [comment] 2020-07-27 08:38
Hi @prdpcrank ,
Thanks for reaching out. 
This is a duplicate of #413 and #406. See the response there for where we left off. Thanks!

Yoyo Lin
MoPub Team

**Comment by niuyaweiqq** [comment] 2020-08-26 02:17
Same problem, looking forward to new information

**Comment by newstrong** [comment] 2020-08-28 08:35
Same problem,please fix it.

**Comment by chauduyphanvu** [comment] 2020-09-11 16:06
@niuyaweiqq, @newstrong — we're aware of this issue and will be addressing it in an upcoming SDK release. Thanks!

**Comment by niuyaweiqq** [comment] 2020-09-24 03:21
When will the new version be available? This bug has affected the use of many users, or is there a solution to reduce the version, and which version can probably solve this problem? Thanks again

**Comment by chauduyphanvu** [comment] 2020-09-24 16:36
@niuyaweiqq, the ETA for the next SDK release that has the fix is early next month. Stay tuned!

**Comment by chauduyphanvu** [comment] 2020-10-01 19:47
This has been fixed in [v5.14.0](https://github.com/mopub/mopub-android-sdk/commit/e8b8d865535855dacd65fdf741e1c0d5b7797ca5). Update and let us know if you continue seeing the issue!

**Closed by chauduyphanvu** 2020-10-01 19:47 UTC
Labels: ADF-5181
