### ISSUE TITLE
Custom Network: Failover for SDK v3.5 and up not working as stated in docs

### ISSUE THREAD

**Issue by aleksanyan** [mopub/mopub-android-sdk#306] opened 2019-02-22 17:58 UTC
One line summary of the issue here

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
* Put failover script described at [https://developers.mopub.com/docs/mediation/custom-networks/#mopub-failover-tag](url) into creative's HTML page
```
<script type="text/javascript" charset="utf-8"> loaded=true; window.location="mopub://failLoad"; </script>
```
* Check mraid checkbox in creative setup page
* load ad tag in sample app

#### Expected behavior:
As stated in [https://developers.mopub.com/docs/mediation/custom-networks/#mraidrich-media-tags](url), it should trigger next line item in waterfall and not count impression.

#### Observed behavior:
SDK is triggering impression and does not trigger next line item in waterfall. Outcome is Blank placement.

#### Evidence:
Happens on every device.

**Comment by dravyan** [comment] 2019-02-22 19:13
Hi @aleksanyan ,
 Could you please let us know whether you have next entry in the waterfall to fallback on if this request fails ?. If you could provide us the credentials to sudo into your account, we will review the setup and get back to you.


Thanks,
Dravya Nataraj
MoPub SDKTeam

**Comment by nabriski** [comment] 2019-02-25 09:51
Hi,

I can confirm that for:
- Version 5.5
- 320x50 Banner Ad Unit
- Where the JS tag creative is:
```javascript
<script type="text/javascript" charset="utf-8"> loaded=true; window.location="mopub://failLoad"; </script>
```
The next item in the waterfall is only called some of the times.
Other times, the SDK appears to determine the ad was loaded correctly.
Not 100% sure but I think that an impression is fired either way.

If it helps, I think both the loaded and failed listeners are called.

Itamar

**Comment by ScottishPig** [comment] 2019-02-25 12:35
I'm having the same issue on iOS ( adViewDidLoadAd being called when an non-guaranteed line item where a failover tag is pasted in ). Were things changed on the MoPub server side?

**Comment by dravyan** [comment] 2019-02-26 18:09
We will look into this further and update once we have more information to share. Thank you for your patience.


Thanks,
Dravya Nataraj
MoPub SDKTeam

**Comment by aleksanyan** [comment] 2019-03-15 10:03
@jeffreycarlson @dravyan Additional feedback regarding *failover*.
As stated in your [docs](https://developers.mopub.com/publishers/mediation/networks/custom-networks/#failover-tag), failover should be called *Synchronously*.
This means, if custom network (ad tag) needs to do API call for getting an ad, it has to do it *synchronously* as well.
But XHR synch API is deprecated, which leads to getting following warning in the webview
```
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
```
So I suppose it's support can be dropped soonish.
Additionally, this forces custom networks (ad tags) to block webview's thread during XHR call, which does not let ad tag trigger *failover* if XHR takes too long for example, thus leading to discrepancy.

Do you maybe consider changing `failover` mechanism in near future? I.e google's DFP does not require *sync* (execution) failover, it can be done async! This leads to the though that Mopub's failover is outdated and / or needs to be redesigned to be easier working with.
#307

**Comment by aleksanyan** [comment] 2019-03-15 12:47
@jeffreycarlson Seems like race condition you've [mentioned](https://github.com/mopub/mopub-android-sdk/issues/307#issuecomment-471618822) is also effecting `interstitial` for mopub SDK 5.5.0 as well.

**Comment by jeffreycarlson** [comment] 2019-03-20 21:30
Yes, agreed and great research! We're looking at options to allow async.

The prevailing thought here is re-enabling the HTML webview on 5.5 via `x-adtype: html` in the ad response for direct and custom network line items. This would re-instate the private MoPub API `finishLoad` that all JS tags were using to override the "load" signaling. That was the defacto async function until we merged the webviews. 

My personal thought is we make that private API publicly supported and port the behavior over to the unified MRAID webview for direct and custom network line items only.

Timing on each of these is TBD and will check in on it again now.

**Comment by FoxLior** [comment] 2019-03-28 09:38
Hi,
Just saw Mopub SDK v5.6 was just released.
Does it fix this issue?
@dravyan

**Comment by dravyan** [comment] 2019-03-28 21:05
@FoxLior , 
This is being worked on at the moment. I will notify here as soon as the fix is available. Thank you!

Thanks,
Dravya Nataraj
MoPub SDKTeam

**Comment by foreza** [comment] 2019-03-29 18:23
Was told to come here from my [ticket](https://github.com/mopub/mopub-ios-sdk/issues/260). I was following this thread as well, suspected I was seeing the same issue but from a different angle. 

@jeffreycarlson , @dravyan  - would appreciate it if we could re-enable the x-adtype: html in the ad response for direct and custom network line items. That way, it remains transparent and not confusing from the usability perspective to us folks who depend on custom network line items. Makes troubleshooting this issue easier for everyone involved, right? 

I've been seeing this issue since early March as well. Would appreciate a resolution soon! It looks like the issue is going to me more of a server-side fix, if I'm not mistaken.

- J

**Comment by aleksanyan** [comment] 2019-04-12 09:40
@jeffreycarlson Thanks for the reply and sharing thoughts. Could you please tell if it's planned to release **Custom network** failover fix with next release?

Regarding `private MoPub API ` mentioned [in comment ](https://github.com/mopub/mopub-android-sdk/issues/306#issuecomment-475036384),
IMHO that's just a way to use Custom network failover in async way, to solve problems described [here](https://github.com/mopub/mopub-android-sdk/issues/306#issuecomment-473227458), and not an attempt to cheat or something.

Both You (Mopub), pubs who integrate your SDK & 3rd party Custom networks are loosing money here since Custom network Is paralyzed since SDK 5.5.0 (around 2 months already).

Just checked the [docs](https://developers.mopub.com/publishers/mediation/networks/custom-networks/) and it still states that Custom network is supported.

**Comment by jeffreycarlson** [comment] 2019-04-18 02:02
@aleksanyan @foreza Thank you for your feedback and questions. We rolled back the server-side change for the affected creative types this afternoon. So `x-adtype: html` has returned for the time being and JavaScript creative in 5.5 and 5.6 SDKs will use the HTML webview (instead of the MRAID webview) and `finishLoad` APIs again. 

Yes, understood that the private API is just a way to use Custom Network failover in an async way. It was never intended to be used externally however we recognize that a number of JS tag providers used this private API anyways. The main point of this change was webview consolidation and to unlock MRAID functionality (thus unlock extra publisher revenue) for these creatives (since the HTML container does not have MRAID APIs). 

Note, we will be moving that API from "private" to "public" in an upcoming release (TBD) and we will be porting the `finishLoad` logic over to the MRAID container so that these custom network JS tags can have access to MRAID APIs. That will allow MoPub to consolidate to one unified MRAID/HTML webview container for all creative types, one that always has MRAID APIs available. When that happens, `x-adtype: html` will no longer be used in ad responses and the HTML/MRAID checkbox in the MoPub UI creative form will be present for backwards compatibility purposes for legacy SDKs. All ad responses for these creative types will have `x-adtype: mraid` or some replacement signaling a unified container. It also means a streamlined SDK codebase, a smaller SDK footprint size and less method counts for Android. 

We appreciate any and all feedback as we work to improve our SDKs and unlock more revenue for our publishers.

**Comment by aleksanyan** [comment] 2019-04-18 05:27
@jeffreycarlson Thank you letting us know & good to hear that. I will be testing that today and will give feedback. 👍

**Comment by aleksanyan** [comment] 2019-04-18 15:29
@jeffreycarlson I confirm it's working & thanks for your efforts!
Where is the best place to follow for news about making `finishLoad` public and MRAID/HTML change?

**Comment by jeffreycarlson** [comment] 2019-04-24 15:48
Great to hear! I'd recommend reviewing the iOS/Android change logs for more details. This change is not likely to ship in 5.7.0. When and where it does, we'll

**Comment by bucksense** [comment] 2019-09-04 14:44
We are facing a problem on Android SDK with FAILOVER  We have configured a custom network in production calling this Mopub CREATIVE 

<div id="bksdivssp"></div>
<script>
 window.location = 'mopub://failLoad';
</script>

As you can see the creative is simply doing a 100% failover.

Using the sample Mopub APP we get the correct behavior and performing 300 tests , they all failover to the next LI and no impression gets attributed to the initial LI.

Once we launch the line item into production with a specific app developer with the same configuration we get a 0.05% cases where the failover fails and the calls are considered an impressions (and billed)

Generating around 30k calls per hour always leaves a 15-40 impressions on the table.

As no calls are made to external entities or JS or images., can you please explain why the failover would not work on specific cases? Is there any logic that we should add to the TAG that would handle better the fail over?

Please assume that the SDK versions present on the app could be also older versions and the lineitem doesn't allow to perform any SDK version targeting. 

Thanks

**Comment by chauduyphanvu** [comment] 2019-09-09 16:43
@bucksense, if you have direct-sold creatives, could you try unchecking the MRAID box on them?

**Comment by bucksense** [comment] 2019-09-09 20:02
Thanks for getting back to us. We have seen this problem with campaigns with the MRAID box ALWAYS NOT UNCHECKED.

**Comment by chauduyphanvu** [comment] 2019-09-26 17:55
@bucksense, thanks for the confirmation. 

I'm suspecting the implementation of the JS might be contributing to the unreliability of the failLoad function not getting called. Would you be able to post the creative here so we can take a look and debug it?

Also, could you confirm the MoPub SDK version(s) that you tried with vs. the one(s) that you saw the buggy failLoad behavior?

**Comment by rsatrasala** [comment] 2019-10-11 20:11
Closing due to inactivity. Please create a new issue if necessary.

**Closed by rsatrasala** 2019-10-11 20:11 UTC
