### ISSUE TITLE
App crash because of  'java.util.ConcurrentModificationException'

### ISSUE THREAD

**Issue by jaakali** [mopub/mopub-android-sdk#361] opened 2019-11-06 10:20 UTC
### Evidence:
```
2019-11-06 21:28:31.083 21956-21956/com.yourcompany.yourapplication D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2019-11-06 21:28:31.087 21956-21956/com.yourcompany.yourapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yourcompany.yourapplication, PID: 21956
    java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
        at com.mopub.mobileads.MoPubRewardedVideoManager$ForEachMoPubIdRunnable.run(MoPubRewardedVideoManager.java:933)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
2019-11-06 21:28:31.087 21956-21956/com.yourcompany.yourapplication I/MMFRuntime: Crash reporting disabled
2019-11-06 21:28:31.119 21956-21956/com.yourcompany.yourapplication I/Process: Sending signal. PID: 21956 SIG: 9
```
this line throw exception. 
https://github.com/mopub/mopub-android-sdk/blob/166b5666cf531647070657aa018efa8c1b57a331/mopub-sdk/mopub-sdk-rewardedvideo/src/main/java/com/mopub/mobileads/MoPubRewardedVideoManager.java#L933

**Comment by jaakali** [comment] 2019-11-06 10:29
It's not a must, but it's possible. I've met it a few times.

**Comment by chauduyphanvu** [comment] 2019-11-06 15:05
@jaakali, could you send over the sample project you used to reproduce that Exception so we can take a look and debug the issue? Thank you!

Vu Chau
MoPub Team

**Comment by jaakali** [comment] 2019-11-07 06:42
@chauduyphanvu 
nothing special, just using 2 different rewarded video units(with same mopub dashboard config) requesting rewarded video, was it because of this? code is in the process of tidying up.

**Comment by chauduyphanvu** [comment] 2019-11-07 19:05
@jaakali, that sounds fine to me. You should be able to use two different ad unit IDs to request rewarded videos. Could you paste some pseudocode showing how your app is making these ad requests and playing those videos?

Also, when is the crash happening (when requesting, caching, playing, rewarding, or closing the video)? We call `ForEachMoPubIdRunnable.run()` in several places depending on the action taken or the state of the video.

**Comment by rsatrasala** [comment] 2019-11-22 23:41
Closing due to inactivity. Feel free to create a new issue if problem exists.

**Closed by rsatrasala** 2019-11-22 23:41 UTC
