### ISSUE TITLE
MoPub sdk not showing waterfall Ad(adColony, Unity)

### ISSUE THREAD

**Issue by rsatrasala** [mopub/mopub-android-sdk#490] opened 2021-08-10 23:25 UTC
### Discussed in https://github.com/mopub/mopub-android-sdk/discussions/487

<div type='discussions-op-text'>

<sup>Originally posted by **AG-Developers** August  4, 2021</sup>
I am using MoPub+FAN+AdColony+Unity.

But mopub showing only FAN ads. Not showing any ads from other networks.

- sdk insert , API verified everything is OK.

Adcolony and unity ads only work in Test device(when i use test mode) otherwise not show ad.
Even not getting any adReq.
 
Pic Proof: (adcolony 168 req from my device that is selected for test ad) and unity without any req.
[![ad-req.jpg](https://i.postimg.cc/L8wjmPNF/ad-req.jpg)](https://postimg.cc/Js3sqGfp)

How can I fix this ??</div>

**Comment by chauduyphanvu** [comment] 2021-08-11 01:21
Duplicate of https://github.com/mopub/mopub-android-sdk/issues/488.

**Closed by chauduyphanvu** 2021-08-11 01:21 UTC
