### ISSUE TITLE
【NPE】AdLifecycleListener$InteractionListener.onAdFailed(com.mopub.mobileads.MoPubErrorCode)' on a null object reference

### ISSUE THREAD

**Issue by JoyHong** [mopub/mopub-android-sdk#406] opened 2020-07-07 10:52 UTC
07-07 12:10:37.613 29492 29492 E AndroidRuntime: FATAL EXCEPTION: main

507-07 12:10:37.613 29492 29492 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mopub.mobileads.AdLifecycleListener$InteractionListener.onAdFailed(com.mopub.mobileads.MoPubErrorCode)' on a null object reference
607-07 12:10:37.613 29492 29492 E AndroidRuntime: at com.mopub.mobileads.MoPubFullscreen.h(MoPubFullscreen.java:182)
707-07 12:10:37.613 29492 29492 E AndroidRuntime: at com.mopub.mobileads.MoPubFullscreen.lambda$Y92JGT4s08fyNPGEn7ZYLWNGVpg(Unknown Source:0)
807-07 12:10:37.613 29492 29492 E AndroidRuntime: at com.mopub.mobileads.-$$Lambda$MoPubFullscreen$Y92JGT4s08fyNPGEn7ZYLWNGVpg.run(Unknown Source:2)
907-07 12:10:37.613 29492 29492 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:808)
1007-07 12:10:37.613 29492 29492 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:101)
1107-07 12:10:37.613 29492 29492 E AndroidRuntime: at android.os.Looper.loop(Looper.java:166)
1207-07 12:10:37.613 29492 29492 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7425)
1307-07 12:10:37.613 29492 29492 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
1407-07 12:10:37.613 29492 29492 E AndroidRuntime: at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
1507-07 12:10:37.613 29492 29492 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by p158276** [comment] 2020-07-08 06:03
Hi @JoyHong ,
Thank you for putting together the bug report. Our team is aware of this issue. 
We’ll circle back when there is an update.

Yoyo Lin,
MoPub Support Team

**Comment by JoyHong** [comment] 2020-07-13 10:57
hi, any update?

**Comment by p158276** [comment] 2020-07-14 02:39
Hi @JoyHong ,
We fixed this internally, and that a fix will ship in an upcoming SDK version.

Yoyo Lin,
MoPub Support Team

**Comment by JoyHong** [comment] 2020-07-23 10:02
The behavior is defined by the product manager，
also before you release the next sdk version, we avoid the issue by checking the expire time.

**Comment by JoyHong** [comment] 2020-07-23 10:11
can u help to check what kind of ad the issue belongs to?
native ad? rewarded video ad? or interstitial ad?

**Comment by ShawnDongAi** [comment] 2020-07-27 01:52
Hi, is there any update?
I also encountered this problem

**Comment by p158276** [comment] 2020-07-27 07:14
Hi @ShawnDongAi 
Thanks for checking. There currently is no update yet. Stay tuned. We will update this thread.
If you encounter this problem, you can try to request and show your ads in a shorter time frame? It should reduce the crash frequency in the meantime.

**Comment by tfkci** [comment] 2020-08-09 20:37
Hi facing the same issue. is there a certain release date for update? returning old sdk recommended? Thanks

**Comment by p158276** [comment] 2020-08-13 16:16
Hi @tfkci ,
We don't have any certain release date now. Will update this thread. 
If your ad scenario cannot request and show your ads in a shorter time frame, returning old sdk could be the last option.

**Comment by simi628** [comment] 2020-08-26 02:37
Hi, which version does not have this problem?

**Comment by p158276** [comment] 2020-08-26 05:07
Hi @simi628 ,
Downgrade to 5.12.0 can be the option if you found that request and show your ads in a shorter time frame doesn't work for you.

**Comment by MixMasterRickyC** [comment] 2020-09-09 14:41
Any news on the fix? You mentioned it was fixed internally in the middle of July, that was nearly two months ago. 
An ETA would be helpful to plan on whether to downgrade or wait for the fix?

**Comment by chauduyphanvu** [comment] 2020-09-09 14:44
@MixMasterRickyC, things are still on track to have this fix shipped with the upcoming SDK release. We don't have an ETA yet, but will update this thread to let you know!

**Comment by Chan2U** [comment] 2020-09-14 02:55
'com.mopub:mopub-sdk:5.13.1‘  crashed again，which version can fix it？

> @MixMasterRickyC, things are still on track to have this fix shipped with the upcoming SDK release. We don't have an ETA yet, but will update this thread to let you know!



> Hi @simi628 ,
> Downgrade to 5.12.0 can be the option if you found that request and show your ads in a shorter time frame didn't work for you.

'com.mopub:mopub-sdk:5.13.1‘  crashed again，which version can fix it？

**Comment by chauduyphanvu** [comment] 2020-09-14 13:27
@Chan2U, the fix will be deployed in the upcoming SDK release.

**Comment by chauduyphanvu** [comment] 2020-10-01 19:49
This has been fixed in [v5.14.0](https://github.com/mopub/mopub-android-sdk/commit/e8b8d865535855dacd65fdf741e1c0d5b7797ca5). Update and let us know if you continue seeing the issue!

**Closed by chauduyphanvu** 2020-10-01 19:49 UTC
Labels: ADF-5181

**Comment by SankarGanesh82** [comment] 2021-04-09 08:55
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void com.mopub.mobileads.AdLifecycleListener$LoadListener.onAdLoaded()' on a null object reference
       at com.mopub.mobileads.MoPubFullscreen$1.onResponse(MoPubFullscreen.java:260)
       at com.mopub.volley.toolbox.ImageLoader$4.run(ImageLoader.java:504)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7656)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

MoPub Unity SDK Version:5.16.4

**Comment by chauduyphanvu** [comment] 2021-04-09 16:53
@SankarGanesh82, please open a separate issue thread with the appropriate details related to your integration, and we should be able to assist. Thank you!

**Comment by 1993xuge** [comment] 2021-05-31 16:22
Is this problem solved?I still have this problem on the latest version.

**Comment by 1993xuge** [comment] 2021-05-31 16:23
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mopub.mobileads.AdLifecycleListener$InteractionListener.onAdFailed(com.mopub.mobileads.MoPubErrorCode)' on a null object reference
       at com.mopub.mobileads.MoPubInline.lambda$load$0(MoPubInline.java:65)
       at com.mopub.mobileads.-$$Lambda$MoPubInline$Xh5Tn8KcyRnQDDLnx6xj9gcOdKM.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7811)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

**Comment by chauduyphanvu** [comment] 2021-06-01 15:42
@1993xuge, please open a separate issue thread with the appropriate details related to your integration, and we should be able to assist. Thank you!
