### ISSUE TITLE
MopubView getWidth return NullPointerException

### ISSUE THREAD

**Issue by haianhsing** [mopub/mopub-android-sdk#347] opened 2019-08-08 03:34 UTC
One line summary of the issue here

- [ yes] I am submitting a bug report for existing functionality
- [ yes] I visited https://developers.mopub.com/ and found no answer
- [ yes] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ yes] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.8.0
#### Android Studio Version:
3.4.1
#### Gradle Version:
5.1.1
#### Device model and OS Version:
Redmi Note 5 Pro   Android7.1.2
Phone2 Android 8.1.0
Fortune 2 Android 8.1.0
Galaxy A5(2016) Android 7.0
moto g(6) plus Android 9
Bolton Android7.1.1
Galaxy Note9 Android 9
more
#### Ad Unit IDs used in reproducing the issue:
c08a168cb38c473bb320c9d8f4197d24
#### Steps to reproduce the behavior:
load banner
#### Expected behavior:
show banner
#### Observed behavior:
app crash
#### Evidence:
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getWidth()' on a null object reference
       at com.mopub.mobileads.MoPubView.l + 4(MoPubView.java:4)
       at a.b.a.d.run + 2(d.java:2)
       at android.os.Handler.handleCallback + 873(Handler.java:873)
       at android.os.Handler.dispatchMessage + 99(Handler.java:99)
       at android.os.Looper.loop + 214(Looper.java:214)
       at android.app.ActivityThread.main + 6981(ActivityThread.java:6981)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main + 1445(ZygoteInit.java:1445)

**Comment by erabhishek** [comment] 2019-08-08 11:11
Do not use `moPubViewObject.setLayoutParams()`

**Comment by chauduyphanvu** [comment] 2019-08-08 15:27
@haianhsing, could you show us the code you use the request the banner or send us a compilable project that we can run to see that crash? Thank you.

Looking at the stack trace, make sure your `MoPubView` instance and/or its parent View is not null. Is there any time where either of them is null?

Vu Chau
MoPub SDK Team

**Comment by Armen101** [comment] 2019-08-09 07:58
I am also facing this problem. Please fix it fast

**Comment by haianhsing** [comment] 2019-08-09 08:19
@chauduyphanvu 

Here is the banner view code I encapsulated:

```
package com.funny.ads;

import android.annotation.SuppressLint;
import android.view.LayoutInflater;
import android.view.View;

import com.funny.base.common.ConfigManager;
import com.funny.base.component.ComponentContext;
import com.funny.base.utils.LogUtils;
import com.module.commercialize.R;
import com.mopub.common.MoPub;
import com.mopub.mobileads.MoPubErrorCode;
import com.mopub.mobileads.MoPubView;

@SuppressWarnings({"unused"})
public class BannerAd {
    private MoPubView mMopubView;
    private String mPlacementId;
    private View mBannerAdView;

    /**
     * 获取banner广告位
     *
     * @return banner广告位
     */
    public String getPlacementId() {
        return mPlacementId;
    }

    /**
     * 获取banner广告View
     *
     * @return banner广告View
     */
    public View getBannerAdView() {
        return mBannerAdView;
    }

    /**
     * 加载banner广告
     *
     * @param placementId 广告位
     * @param listener    事件回调
     */
    @SuppressLint("InflateParams")
    public void load(String placementId, final BannerAdListener listener) {
        if (ConfigManager.getInstance().isAdDisable()) {
            return;
        }
        if (!MoPub.isSdkInitialized() && listener != null) {
            listener.onFailed(null, "CommercializeSDK is currently initializing.");
            return;
        }
        mPlacementId = placementId;
        mMopubView = ((MoPubView) LayoutInflater.from(ComponentContext.getContext()).inflate(R.layout.layout_banner_ad, null));
        mMopubView.setAdUnitId(placementId);
        mMopubView.setBannerAdListener(new MoPubView.BannerAdListener() {
            @Override
            public void onBannerLoaded(MoPubView moPubView) {
                LogUtils.i("onBannerLoaded");
                mBannerAdView = moPubView;
                if (listener != null) {
                    listener.onLoaded(BannerAd.this);
                }
            }

            @Override
            public void onBannerFailed(MoPubView moPubView, MoPubErrorCode moPubErrorCode) {
                LogUtils.i("onBannerFailed: " + moPubErrorCode);
                if (listener != null) {
                    listener.onFailed(BannerAd.this, moPubErrorCode.toString());
                }
            }

            @Override
            public void onBannerClicked(MoPubView moPubView) {
                LogUtils.i("onBannerClicked");
                if (listener != null) {
                    listener.onClicked(BannerAd.this);
                }
            }

            @Override
            public void onBannerExpanded(MoPubView moPubView) {
                LogUtils.i("onBannerExpanded");
                if (listener != null) {
                    listener.onExpanded(BannerAd.this);
                }
            }

            @Override
            public void onBannerCollapsed(MoPubView moPubView) {
                LogUtils.i("onBannerCollapsed");
                if (listener != null) {
                    listener.onCollapsed(BannerAd.this);
                }
            }
        });
        mMopubView.loadAd();
        LogUtils.i("loadBanner");
    }

    /**
     * 销毁banner广告
     */
    public void destroy() {
        if (mMopubView != null) {
            mMopubView.destroy();
            mMopubView = null;
        }
        if (mBannerAdView != null) {
            mBannerAdView = null;
        }
    }

    /**
     * 设置测试模式
     *
     * @param testing 是否测试模式
     */
    public void setTesting(boolean testing) {
        if (mMopubView != null) {
            mMopubView.setTesting(testing);
        }
    }

    /**
     * 设置自动刷新
     *
     * @param enabled 是否自动刷新
     */
    public void setAutoRefreshEnabled(boolean enabled) {
        if (mMopubView != null) {
            mMopubView.setAutorefreshEnabled(enabled);
        }
    }

    public interface BannerAdListener {
        void onLoaded(BannerAd bannerAd);

        void onFailed(BannerAd bannerAd, String msg);

        void onClicked(BannerAd bannerAd);

        void onExpanded(BannerAd bannerAd);

        void onCollapsed(BannerAd bannerAd);
    }
}

```

Here is the layout_banner_ad.xml code:

```
<?xml version="1.0" encoding="utf-8"?>
<com.mopub.mobileads.MoPubView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/banner"
    android:layout_width="match_parent"
    android:layout_height="50dp"
    app:moPubAdSize="height_50">

</com.mopub.mobileads.MoPubView>
```

Here is the code I call to show banner ad view:

```
     private LinearLayout mAdContainer;
     private BannerAd mBannerAd;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        mAdContainer = findViewById(R.id.ad_container);
        showBannerAd();
    }

    private void showBannerAd() {
        mBannerAd = new BannerAd();
        mBannerAd.load(BANNER_AD_PLACEMENT_ID, new BannerAd.BannerAdListener() {
            @Override
            public void onLoaded(BannerAd bannerAd) {
                if (bannerAd != null && bannerAd.getBannerAdView() != null) {
                    mAdContainer.removeAllViews();
                    mAdContainer.addView(bannerAd.getBannerAdView());
                }
            }

            @Override
            public void onFailed(BannerAd bannerAd, String msg) {

            }

            @Override
            public void onClicked(BannerAd bannerAd) {

            }

            @Override
            public void onExpanded(BannerAd bannerAd) {

            }

            @Override
            public void onCollapsed(BannerAd bannerAd) {

            }
        });
    }

    @Override
    protected void onDestroy() {
        if (mBannerAd != null) {
            mBannerAd.destroy();
            mBannerAd=null;
        }
        super.onDestroy();
    }
```

Here is the activity_main.xml code: 

```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/parent"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:ignore="MissingConstraints">

    <LinearLayout
        android:id="@+id/ad_container"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintStart_toStartOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>
```

Hope to help you locate errors.

**Comment by haianhsing** [comment] 2019-08-09 08:22
@erabhishek 
where and how to do this. Can you tell me more about it?Thanks!

**Comment by chauduyphanvu** [comment] 2019-08-09 21:09
@haianhsing, it looks like a parent view of your `MoPubView` instance (`mAdContainer`?) might be null at the time of the ad request. Could you place a breakpoint on `mAdContainer` and check if it ever becomes null?

If you can reproduce the crash yourself, could you send me that project? It makes more sense to debug a runnable app to diagnose the crash more quickly.

**Comment by SoftNirav** [comment] 2019-08-10 13:14
I was using a fragment, and experiencing the same issue.
I had to move the code from onCreateView() to onStart() and it was solved.
Try doing that.

**Comment by haianhsing** [comment] 2019-08-12 07:01
@chauduyphanvu Unfortunately, I can‘t reproduce the crash myself. In addition, I initialize mAdContainer at onCreate method in my activity and never Explicitly set to null. Finally, I find that only load or refresh the ad will run the code causing crash. So I decide to prohibit autorefresh.

**Comment by chauduyphanvu** [comment] 2019-08-12 14:15
@haianhsing, thanks for letting us know. We will be internally guarding against a NullPointerException for `getWidth()` and `getHeight()` from `MoPubView.java`, so be sure to upgrade when the next SDK is live to avoid this crash.

**Comment by haianhsing** [comment] 2019-08-13 09:21
@chauduyphanvu OK, Thanks.

**Closed** 2019-08-16 20:20 UTC
