### ISSUE TITLE
E/Volley: [37820] NetworkDispatcher.processRequest: Unhandled exception java.lang.RuntimeException: Bad URL 

### ISSUE THREAD

**Issue by vikasrairajput** [mopub/mopub-android-sdk#308] opened 2019-03-17 08:20 UTC
E/Volley: [37820] NetworkDispatcher.processRequest: Unhandled exception java.lang.RuntimeException: Bad URL 
                                                                            java.lang.RuntimeException: Bad URL 
                                                                                at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:171)
                                                                                at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:120)
                                                                                at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:87)
                                                                             Caused by: java.net.MalformedURLException: Protocol not found: 
                                                                                at java.net.URL.<init>(URL.java:176)
                                                                                at java.net.URL.<init>(URL.java:125)
                                                                                at com.mopub.volley.toolbox.HurlStack.executeRequest(HurlStack.java:92)
                                                                                at com.mopub.network.RequestQueueHttpStack.executeRequest(RequestQueueHttpStack.java:57)
                                                                                at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:131)
                                                                                at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:120) 
                                                                                at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:87) 

I m also getting Unspecified error occurred in onNativeFail()

here is my code

    private void loadNativeAD(){
        ViewBinder viewBinder = new ViewBinder.Builder(R.layout.native_ad_layout)
                .mainImageId(R.id.native_ad_main_image)
                .iconImageId(R.id.native_ad_icon_image)
                .titleId(R.id.native_ad_title)
                .textId(R.id.native_ad_text)
                .privacyInformationIconImageId(R.id.native_ad_privacy_information_icon_image)
                .build();

        MoPubNative moPubNative = new MoPubNative(context, "21a75669922f4679b4a152259533e104", new MoPubNative.MoPubNativeNetworkListener() {
            @Override
            public void onNativeLoad(com.mopub.nativeads.NativeAd nativeAd) {
                Log.e(TAG,"onNatibveLoad");
            }

            @Override
            public void onNativeFail(NativeErrorCode errorCode) {
                Log.e(TAG,"onNativeFail"+errorCode);
            }
        });
        moPubNative.registerAdRenderer(new MoPubStaticNativeAdRenderer(viewBinder));

        moPubNative.makeRequest(new RequestParameters.Builder()
                .desiredAssets(EnumSet.of(
                        RequestParameters.NativeAdAsset.TITLE,
                        RequestParameters.NativeAdAsset.TEXT,
                        RequestParameters.NativeAdAsset.MAIN_IMAGE,
                        RequestParameters.NativeAdAsset.CALL_TO_ACTION_TEXT))
                .build());
    }

**Comment by chauduyphanvu1** [comment] 2019-03-19 15:31
@vikasrairajput - your code looks fine to me. We released v5.6.0 of the SDK yesterday that shipped with a new Volley - could you update to the new version and let us know if you still see the crash? If the crash persists, could you send us a zipped build that reproduces it? Thank you!

Vu Chau
MoPub SDK Team

**Comment by rashedlone** [comment] 2019-04-03 13:17
I'm using 5.6.0, I still get same error. Any suggestions?

**Comment by chauduyphanvu1** [comment] 2019-04-03 14:36
@rashedlone, it looks like the ad request doesn't have a protocol (`java.net.MalformedURLException: Protocol not found`). I managed to reproduced a very similar problem; I got back `java.net.MalformedURLException: no protocol` instead by simply leaving out the `HTTPS://` protocol of the ad request URL after it's constructed but before it hits Volley to be executed.

If you have a network proxy tool (like [Charles](https://www.charlesproxy.com/)), when you get that `MalformedURLException`, check in Charles at the same time to see what the ad request URL is. Feel free to share it with us so we can trace back the creative(s) involved. This does not seem to be an SDK issue since we are catching the Exception (it's just not handled).

**Comment by vikasrairajput** [comment] 2019-04-05 15:40
I m still facing the same issue after library update and  I also cant any URL  related to mopub library using charles

**Comment by wyattwww** [comment] 2019-04-17 23:20
I suspect this is because of Android 9's new HTTPS network security that's breaking the ad requests.  It was working until I upgraded to 9.

**Comment by chauduyphanvu1** [comment] 2019-04-23 15:12
@wyattwww, thanks for letting us know. The original issue description details a "Protocol not found" error, but the [Android 9 HTTPS enforcement](https://developers.mopub.com/publishers/android/get-started/#step-4-add-a-network-security-configuration-file) assumes that you already have either the HTTP/HTTPS protocol so it might not be the same issue. 

If you do see error with HTTPs on Android 9 specifically, check out the linked tutorial to handle exceptions for certain domains. If you need help, feel free to open a separate issue report and we'll take a look. Thank you!

**Comment by Mandrakia** [comment] 2019-04-26 12:54
Same issue here, wanted to add Mopub to my app but every request has this error. Bad Url, no protocol.

**Comment by Mandrakia** [comment] 2019-04-26 13:07
There's a bug in MultiAdRequest.java, the constructor parameter (url) is not used and not assigned to mUrl

**Comment by therealandroid** [comment] 2019-04-30 17:37
This problem also happened to me. I looked at other versions of my code and found that I never needed to initialize the Mopub SDK for it to work, and I believe that after this new version (5.6) this became mandatory, but I'm not sure.
 
This is how I've solved my problem:

```
SdkConfiguration sdkConfiguration = new SdkConfiguration.Builder("MOPUB_ID")
                .withLogLevel(MoPubLog.LogLevel.DEBUG)
                .withLegitimateInterestAllowed(false)
                .build();

        MoPub.initializeSdk(this, sdkConfiguration, new SdkInitializationListener() {
            @Override
            public void onInitializationFinished() {
                Log.d("Mopub", "SDK initialized");
            }
        });
```
[Oficial documentation here](https://developers.mopub.com/publishers/android/initialize/)

**Comment by chauduyphanvu1** [comment] 2019-04-30 18:11
Thanks for letting us know. Ensure that the SDK has been initialized before making any ad requests. We expect that ad requests will fail otherwise.

If you get back an empty URL or one without a protocol, that would be a separate problem that needs to be investigated on a different issue report.

@vikasrairajput - do you still see this issue? Let us know if you still need assistance.

**Comment by perry83** [comment] 2019-05-06 10:15
I experience exactly the same issue with the latest SDK. I'm initilizing SDK, but still see an error saying "Bad URL".

**Comment by chauduyphanvu1** [comment] 2019-05-06 13:17
@perry83, could you paste your initialization (and also ad request) code here as well as the full error log? You can also attach a networking session ([Charles](https://www.charlesproxy.com/)) that shows the bad URL and its content. Thank you.

**Comment by perry83** [comment] 2019-05-08 17:29
Hi @chauduyphanvu1 ,

below is my initialization code in Kotlin:

`override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val sdkConfiguration = SdkConfiguration.Builder("AD_UNIT_HERE").build()
        MoPub.initializeSdk(this, sdkConfiguration, initSdkListener())

        moPubInterstitial = MoPubInterstitial(this, "AD_UNIT_HERE")
        moPubInterstitial!!.interstitialAdListener = this
        moPubInterstitial!!.load()
    }

private fun initSdkListener(): SdkInitializationListener {
        return SdkInitializationListener {
        }
    }`

And here is the error log:

2019-05-08 19:25:04.119 5378-5538/app E/Volley: [315] NetworkDispatcher.processRequest: Unhandled exception java.lang.RuntimeException: Bad URL 
    java.lang.RuntimeException: Bad URL 
        at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:143)
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
        at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
     Caused by: java.net.MalformedURLException: no protocol: 
        at java.net.URL.<init>(URL.java:590)
        at java.net.URL.<init>(URL.java:487)
        at java.net.URL.<init>(URL.java:436)
        at com.mopub.volley.toolbox.HurlStack.executeRequest(HurlStack.java:87)
        at com.mopub.network.RequestQueueHttpStack.executeRequest(RequestQueueHttpStack.java:57)
        at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:91)
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132) 
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111) 
        at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:90) 
2019-05-08 19:25:04.361 5378-5378/app D/MoPubInterstitial: onInterstitialFailed, Error Code: 10000, Error Name: UNSPECIFIED

**Comment by perry83** [comment] 2019-05-08 17:31
I can't see any request being sent to ad server. Seems like the error prevents sending this request.

**Comment by chauduyphanvu1** [comment] 2019-05-08 19:07
I reproduced that crash in https://github.com/mopub/mopub-android-sdk/issues/308#issuecomment-479517061, but because I never got any URL on this thread to try out, it's not yet final to say what exactly might be causing the `no protocol` crash. 

@perry83, if you can reproduce the crash yourself, my suggestion is to put a breakpoint at `com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:143)` to see what the URL might be. Once we have the URL, we will know what's firing it and identify why it doesn't have a protocol. My other suggestion is to only send out the ad request once the MoPub initialization has completed. From your code, it looks like you're requesting ads right away without waiting for a callback from MoPub.

**Comment by perry83** [comment] 2019-05-08 21:21
You were right. It was a matter of initialization.

When I load the add after MoPub is initialized, then I have another issue:
D/MoPubInterstitial: onInterstitialFailed, Error Code: 10000, Error Name: NO_FILL

But that means that there is no ad that could be displayed. What is the fill rate of MoPub ad network?

**Comment by chauduyphanvu1** [comment] 2019-05-08 21:34
That's likely not a related result of the move to making ad requests after MoPub's initialization. In fact, making ad requests after the SDK has finished initializing is the only way (if you check for debug log, the MoPub SDK should be logging something explaining that ad requests aren't made before initialization completes).

Check out other ad unit IDs or use our [sample ad unit ID](https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sample/res/values/strings.xml#L26) to test your integration.

**Comment by rsatrasala** [comment] 2019-06-21 20:48
Closing. Please open a new issue if needed.

**Closed by rsatrasala** 2019-06-21 20:48 UTC
