### ISSUE TITLE
Battery drain and device becomming hot because of the ad banner

### ISSUE THREAD

**Issue by theboubougne** [mopub/mopub-android-sdk#467] opened 2021-04-08 17:50 UTC
Battery drain and device becomming hot because of the ad banner

#### MoPub SDK Version:
5.16.4

Since upgrdaing to 5.16.x some user are experiencing huge data drain and their device becoming hot.
The logs are login this kind of content like crazy
Battery drain and device becomming hot because of the ad banner

2021-04-08 08:12:10.965 11891-29071/com.xxx D/a.xxx: PlayerBase::stop() from IPlayer
2021-04-08 08:12:10.965 11891-29071/com.xxx D/AAudio: AAudioStream_close(s#12370) called ---------------
2021-04-08 08:12:10.965 11891-29071/com.xxx D/AAudioStream: setState(s#12370) from 13 to 11
2021-04-08 08:12:10.965 11891-29071/com.xxx D/AAudioStream: setState(s#12370) from 11 to 12
2021-04-08 08:12:10.966 11891-29071/com.xxx D/AAudio: AAudioStream_close(s#12370) returned 0 ---------
2021-04-08 08:12:10.967 11891-29071/com.xxx I/AAudio: AAudioStreamBuilder_openStream() called ----------------------------------------
2021-04-08 08:12:10.967 11891-29071/com.xxx I/AudioStreamBuilder: rate   =  48000, channels  = 2, format   = 5, sharing = SH, dir = OUTPUT
2021-04-08 08:12:10.967 11891-29071/com.xxx I/AudioStreamBuilder: device =      0, sessionId = -1, perfMode = 10, callback: ON with frames = 192
2021-04-08 08:12:10.967 11891-29071/com.xxx I/AudioStreamBuilder: usage  =      1, contentType = 0, inputPreset = 0, allowedCapturePolicy = 0
2021-04-08 08:12:10.967 11891-29071/com.xxx I/AudioStreamBuilder: privacy sensitive = false
2021-04-08 08:12:10.967 11891-29071/com.xxx D/AudioStreamBuilder: build() MMAP not used because AAUDIO_PERFORMANCE_MODE_LOW_LATENCY not requested.
2021-04-08 08:12:10.967 11891-29071/com.xxx D/a.xxx: PlayerBase::PlayerBase()
2021-04-08 08:12:10.967 11891-29071/com.xxx D/AudioStreamTrack: open(), request notificationFrames = 192, frameCount = 192
2021-04-08 08:12:10.975 11891-29071/com.xxx D/AudioTrack: setVolume(1.000000, 1.000000) pid : 11891
2021-04-08 08:12:10.975 11891-29071/com.xxx D/AAudioStream: setState(s#12371) from 0 to 2
2021-04-08 08:12:10.977 11891-29071/com.xxx I/AAudio: AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#12371 ----------------
2021-04-08 08:12:10.977 11891-29071/com.xxx D/AAudio: AAudioStream_requestStart(s#12371) called --------------
2021-04-08 08:12:10.977 11891-29071/com.xxx D/AAudioStream: setState(s#12371) from 2 to 3
2021-04-08 08:12:10.978 11891-29071/com.xxx D/a.xxx: PlayerBase::start() from IPlayer
2021-04-08 08:12:10.978 11891-29071/com.xxx D/AAudio: AAudioStream_requestStart(s#12371) returned 0 ---------
2021-04-08 08:12:10.980 11891-11891/com.xxx V/MediaRouter: Selecting route: RouteInfo{ name=Tablet, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
2021-04-08 08:12:10.981 11891-31869/com.xxx D/AudioStreamLegacy: onAudioDeviceUpdate() devId 24 => 2
2021-04-08 08:12:10.981 11891-31869/com.xxx D/AudioStreamLegacy: onAudioDeviceUpdate() request DISCONNECT in data callback due to device change
2021-04-08 08:12:10.985 11891-25806/com.xxx D/AudioStreamLegacy: checkForDisconnectRequest() mRequestDisconnect acknowledged
2021-04-08 08:12:10.985 11891-25806/com.xxx D/AAudioStream: setState(s#12371) from 3 to 13
2021-04-08 08:12:10.986 11891-25806/com.xxx W/AudioStreamLegacy: processCallbackCommon() data, stream disconnected
2021-04-08 08:12:10.986 11891-25806/com.xxx E/AudioTrack: processAudioBuffer(36746): EVENT_MORE_DATA requested 64 bytes but callback returned -1 bytes
2021-04-08 08:12:10.986 11891-29071/com.xxx D/AAudio: AAudioStream_requestStop(s#12371) called
2021-04-08 08:12:10.986 11891-29071/com.xxx D/AAudioStream: setState(s#12371) from 13 to 9
2021-04-08 08:12:10.986 11891-29071/com.xxx E/AAudioStream: setState(12371) tried to set to 9 but already DISCONNECTED
2021-04-08 08:12:10.986 11891-29071/com.xxx D/AudioTrack: stop(36746): called with 3840 frames delivered
2021-04-08 08:12:10.986 11891-29071/com.xxx D/a.xxx: PlayerBase::stop() from IPlayer
2021-04-08 08:12:10.986 11891-29071/com.xxx D/AAudio: AAudioStream_close(s#12371) called ---------------
2021-04-08 08:12:10.986 11891-29071/com.xxx D/AAudioStream: setState(s#12371) from 13 to 11
2021-04-08 08:12:10.986 11891-29071/com.xxx D/AAudioStream: setState(s#12371) from 11 to 12
2021-04-08 08:12:10.990 11891-29071/com.xxx D/AAudio: AAudioStream_close(s#12371) returned 0 ---------
2021-04-08 08:12:10.990 11891-29071/com.xxx I/AAudio: AAudioStreamBuilder_openStream() called ----------------------------------------
2021-04-08 08:12:10.990 11891-29071/com.xxx I/AudioStreamBuilder: rate   =  48000, channels  = 2, format   = 5, sharing = SH, dir = OUTPUT
2021-04-08 08:12:10.990 11891-29071/com.xxx I/AudioStreamBuilder: device =      0, sessionId = -1, perfMode = 10, callback: ON with frames = 192
2021-04-08 08:12:10.990 11891-29071/com.xxx I/AudioStreamBuilder: usage  =      1, contentType = 0, inputPreset = 0, allowedCapturePolicy = 0
2021-04-08 08:12:10.990 11891-29071/com.xxx I/AudioStreamBuilder: privacy sensitive = false
2021-04-08 08:12:10.990 11891-29071/com.xxx D/AudioStreamBuilder: build() MMAP not used because AAUDIO_PERFORMANCE_MODE_LOW_LATENCY not requested.
2021-04-08 08:12:10.990 11891-29071/com.xxx D/a.xxx: PlayerBase::PlayerBase()
2021-04-08 08:12:10.991 11891-29071/com.xxx D/AudioStreamTrack: open(), request notificationFrames = 192, frameCount = 192
2021-04-08 08:12:10.999 11891-29071/com.xxx D/AudioTrack: setVolume(1.000000, 1.000000) pid : 11891
2021-04-08 08:12:10.999 11891-29071/com.xxx D/AAudioStream: setState(s#12372) from 0 to 2
2021-04-08 08:12:11.000 11891-29071/com.xxx I/AAudio: AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#12372 ----------------
2021-04-08 08:12:11.001 11891-29071/com.xxx D/AAudio: AAudioStream_requestStart(s#12372) called --------------
2021-04-08 08:12:11.001 11891-29071/com.xxx D/AAudioStream: setState(s#12372) from 2 to 3
2021-04-08 08:12:11.006 11891-29071/com.xxx D/a.xxx: PlayerBase::start() from IPlayer
2021-04-08 08:12:11.006 11891-29071/com.xxx D/AAudio: AAudioStream_requestStart(s#12372) returned 0 ---------
2021-04-08 08:12:11.006 11891-31869/com.xxx D/AudioStreamLegacy: onAudioDeviceUpdate() devId 24 => 2
2021-04-08 08:12:11.006 11891-31869/com.xxx D/AudioStreamLegacy: onAudioDeviceUpdate() request DISCONNECT in data callback due to device change
2021-04-08 08:12:11.007 11891-25807/com.xxx D/AudioStreamLegacy: checkForDisconnectRequest() mRequestDisconnect acknowledged
2021-04-08 08:12:11.007 11891-25807/com.xxx D/AAudioStream: setState(s#12372) from 3 to 13
2021-04-08 08:12:11.007 11891-25807/com.xxx W/AudioStreamLegacy: processCallbackCommon() data, stream disconnected
2021-04-08 08:12:11.007 11891-25807/com.xxx E/AudioTrack: processAudioBuffer(36747): EVENT_MORE_DATA requested 1536 bytes but callback returned -1 bytes
2021-04-08 08:12:11.007 11891-29071/com.xxx D/AAudio: AAudioStream_requestStop(s#12372) called
2021-04-08 08:12:11.007 11891-29071/com.xxx D/AAudioStream: setState(s#12372) from 13 to 9
2021-04-08 08:12:11.007 11891-29071/com.xxx E/AAudioStream: setState(12372) tried to set to 9 but already DISCONNECTED
2021-04-08 08:12:11.007 11891-29071/com.xxx D/xxx: stop(36747): called with 0 frames delivered
2021-04-08 08:12:11.007 11891-29071/com.xxx D/a.xxx: PlayerBase::stop() from IPlayer
2021-04-08 08:12:11.007 11891-29071/com.xxx D/AAudio: AAudioStream_close(s#12372) called ---------------
2021-04-08 08:12:11.007 11891-29071/com.xxx D/AAudioStream: setState(s#12372) from 13 to 11
2021-04-08 08:12:11.007 11891-29071/com.xxx D/AAudioStream: setState(s#12372) from 11 to 12
2021-04-08 08:12:11.008 11891-29071/com.xxx D/AAudio: AAudioStream_close(s#12372) returned 0 ---------

As soon as I disable the Mopub ad banner the logs stop

**Comment by chauduyphanvu** [comment] 2021-04-09 19:18
@theboubougne, how did you reproduce that issue (is there an ad unit ID to try and what are the steps to do)? How often are you requesting and showing ads?

Vu Chau
MoPub Team

**Comment by theboubougne** [comment] 2021-04-09 19:30
Lots of users have been reporting this. If I keep the screen turned on,
then at some point the logs will start pouring like crazy with those
errors. As a result the device gets warm and the battery drain way faster
that usual.

This happens on a banner format with a 30d refresh rate

**Comment by chauduyphanvu** [comment] 2021-04-14 14:11
@theboubougne, this might be specific to the ads that are served at that time, so without an ad unit ID to reproduce the issue it'll be hard for us to assist you. 

Alternatively, if you are able to reproduce this behavior locally, feel free to share with us additional details like a Charles log showing the MoPub network traffic. If we have details on the kind of ads served, we can take some actions on our end as well.

**Comment by m-melis** [comment] 2021-04-16 08:12
I saw this with the banner test ad in the emulator. Without the banner, everything fine, but after displaying it the emulator basically hangs after a short time. In a real device, the result is probably quick battery drain.

**Comment by theboubougne** [comment] 2021-04-16 17:22
Users experiencing this had their battery kille very quickly and the device
got very hot to the touch.
Never experienced this before the last release of Mopub SDK

**Comment by chauduyphanvu** [comment] 2021-04-16 21:38
Do you have an ad unit ID with which you saw the above issue? Without one, it'll be very hard to speculate on the cause of the issue.

**Comment by chauduyphanvu** [comment] 2021-04-27 22:25
Closing the issue due to irreproducibility. Feel free to reopen if needed.

**Closed by chauduyphanvu** 2021-04-27 22:25 UTC
