### ISSUE TITLE
Native memory leak

### ISSUE THREAD

**Issue by GlebMaltsev** [mopub/mopub-android-sdk#433] opened 2020-09-29 14:50 UTC
MoPub Banners drain out memory when app just resting on the screen where there's MoPub ad banner. Issue can be reproduced on the latest version of sample app (see attachements below).

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.12.0, 5.13.1

#### Android Studio Version:
4.0.1

#### Gradle Version:
5.6.4, 6.1.1

#### Device model and OS Version:
HUAWEI P8 lite with Android 7.0, Sony Xperia Z2 with Android 5.1.1

#### Ad Unit IDs used in reproducing the issue:
id for test ad banner: b195f8dd8ded45fe847ad89ed1d016da

#### Steps to reproduce the behavior:
1. Build [MoPub sample project](https://github.com/mopub/mopub-android-sdk/tree/master/mopub-sample);
2. Launch it on the device;
3. Open screen with banners ads;
4. Wait some minutes;

#### Expected behavior:
App not lagging, memory consumption is stable.

#### Observed behavior:
App freeze, the more you are staying on the screen the bigger lags occur. After some point of time device becomes almost irresponsible and you will not even able to collapse and kill the app - you need to do force reset of the device. AS profile show stable increase of native memory consumption.

#### Evidence:
Example of the screen with banner ads from MoPub sample project:
<img src="https://user-images.githubusercontent.com/15730507/94571720-ee2a1b00-0278-11eb-9887-25338d89a808.png" width="270" height="480">

Leaving the app on this screen for 15 minutes give me the following memory consumption chart:
![image](https://user-images.githubusercontent.com/15730507/94571937-24679a80-0279-11eb-9efc-52008a062d36.png)

#### Additional details:
- Moving outside from the screen with banner ads will not free up memory;
- Issue appear with MoPub test ad unit id which means that the problem is in MoPub SDK itself, not in mediators;
- Issue is 9\10 reproducable on some devices (including those I listed above) and not reproducable on another devices (for example, I was not able to reproduce the issue on my Nokia 6.1 with Android 10 and LG Nexus 5 with Android 6.0);
- Setting **MoPubView.autorefreshEnabled = false** doesn't resolve the problem - banner ad stop blinking (during refreshing), however native memory consumption show the same growing;
- While writing this issue (~30 minutes), native memory consumption on the device running MoPub sample app became 0.9GB;

**Comment by chauduyphanvu** [comment] 2020-10-05 17:47
@GlebMaltsev, thanks for letting us know! I'll relay your observation to the rest of the team to see if we can do something here. 

But, most of what you described is actually expected given the more ads you are loading and showing. It is reasonable to anticipate a spike in memory consumption.

In real world use cases, implementations differ widely in terms of how and where banners are requested and displayed. Additionally, specific devices / Android implementations might have their own ways to manage memory. Make sure that you have properly called `destroy()` on your `MoPubView` instance, and set it to `null` upon leaving the screen.

Vu Chau
MoPub Team

**Comment by GlebMaltsev** [comment] 2020-10-05 22:21
Hi Vu Chau

As I mentioned in the issue, memory leak occur during staying on the screen so there's no reason why I need to call _destroy()_. Also I mentioned that issue occur even if we disable refreshing of the ads which means that memroy leak doesn't related to additional ads loading.

**Comment by chauduyphanvu** [comment] 2020-10-16 19:24
@GlebMaltsev, I was referring to the case where you said:

> Moving outside from the screen with banner ads will not free up memory

Could you confirm if `destroy()` is in fact called? The expectation is that memory will be freed up at that point in time. Let us know if you see otherwise.

Other than that, the rest of your observation is consistent with the way the SDK is designed to work. In real world use cases, users typically do not stay on the same screen for an indefinite amount of time, so as they navigate away the MoPub SDK will attempt to release system resources.

**Comment by GlebMaltsev** [comment] 2020-10-17 10:59
Yes, I can confirm that destroy() is in fact called. However, the main problem here is not in calling or not calling destroy(), but in fact that memory consumption is growing up to inadequate values during staying on screen with banner ads.

**Comment by rajsuvariya** [comment] 2020-10-21 05:01
Also, I have also seen that MoPubInterstitial is holding Activity context but when we call destroy() it is not dereferenced. It is leading to memory leak.

**Comment by chauduyphanvu** [comment] 2020-11-02 14:45
@rajsuvariya, please open a separate GitHub Issue for that behavior so we can fully investigate. Thanks!

@GlebMaltsev, `in fact that memory consumption is growing up to inadequate values during staying on screen with banner ads.` --> this is expected like I said previously. The more ads you load, the more WebViews are spawned, and that leads to a higher memory consumption.

**Comment by GlebMaltsev** [comment] 2020-11-02 18:05
> The more ads you load, the more WebViews are spawned, and that leads to a higher memory consumption.

But I guess that since SDK is showing only one banner in any moment of time, as soon as new WebView has been spawned and become visible, old one should be destroyed and memory should be released. You shouldn't keep all old WebView in memory, otherwise this will lead to OOM crash if user will stay on the screen too long.

**Comment by UgurLuckSkyGok** [comment] 2020-11-03 13:53
![Native](https://user-images.githubusercontent.com/45621741/97993074-9e4cef80-1df4-11eb-9d2e-df4571985119.png)
I have same problem. Native Heap is constantly increasing and crashes after a certain period of time.
v. 5.14.1

**Comment by chauduyphanvu** [comment] 2020-11-06 20:58
@GlebMaltsev, thanks for your feedback. I will relay it to the rest of the team.

@UgurLuckSkyGok, are you able to provide any reproducing steps with which you saw the memory spike?

**Comment by UgurLuckSkyGok** [comment] 2020-11-10 09:32
@chauduyphanvu I am getting the same error. If there is a playable ad, there is no accumulation, but there is accumulation in the transition and reward ads. And it crashes. Mopub does the same on the empty project.

**Comment by chauduyphanvu** [comment] 2020-11-13 22:46
@UgurLuckSkyGok, are you able to provide a project (and workflow) with which you saw the issue?

**Comment by andj207** [comment] 2020-11-23 16:17
My app leaks the MainActivity because of MoPubFullScreen (used with Interstitial and Rewarded ads) and I've tried all destroy things but could not help. So I decided to download the sample code and run. It actually leak the MoPobSampleActivity. 

I use LeakCanary for the sample project and here are the results.

My destroy code (latest MoPub full sdk version), and I confirmed both destroy codes were invoked
   
    // Interstitial
    interstitialAd?.interstitialAdListener = null
    interstitialAd?.destroy()
    interstitialAd = null

    // Rewarded video
    MoPubRewardedVideos.setRewardedVideoListener(null)

**My app leak:**

    ====================================
    HEAP ANALYSIS RESULT
    ====================================
    1 APPLICATION LEAKS
    References underlined with "~~~" are likely causes.
    Learn more at https://squ.re/leaks.
    2303371 bytes retained by leaking objects
    Signature: f751aa6fbaa07bb6b9e71e3816b6946846ccc65d
    ┬───
    │ GC Root: Global variable in native code
    │
    ├─ android.database.ContentObserver$Transport instance
    │    Leaking: UNKNOWN
    │    Retaining 609 bytes in 5 objects
    │    ↓ ContentObserver$Transport.mContentObserver
    │                                ~~~~~~~~~~~~~~~~
    ├─ com.iab.omid.library.mopub.a.d instance
    │    Leaking: UNKNOWN
    │    Retaining 81 bytes in 4 objects
    │    a instance of com.myapp.MainApplication
    │    ↓ d.d
    │        ~
    ├─ com.iab.omid.library.mopub.b.f instance
    │    Leaking: UNKNOWN
    │    Retaining 44 bytes in 3 objects
    │    ↓ f.f
    │        ~
    ├─ com.iab.omid.library.mopub.b.a instance
    │    Leaking: UNKNOWN
    │    Retaining 2317969 bytes in 31800 objects
    │    ↓ a.b
    │        ~
    ├─ java.util.ArrayList instance
    │    Leaking: UNKNOWN
    │    Retaining 60 bytes in 2 objects
    │    ↓ ArrayList.elementData
    │                ~~~~~~~~~~~
    ├─ java.lang.Object[] array
    │    Leaking: UNKNOWN
    │    Retaining 40 bytes in 1 objects
    │    ↓ Object[].[0]
    │               ~~~
    ├─ com.iab.omid.library.mopub.adsession.a instance
    │    Leaking: UNKNOWN
    │    Retaining 2317833 bytes in 31795 objects
    │    ↓ a.b
    │        ~
    ├─ com.iab.omid.library.mopub.adsession.AdSessionContext instance
    │    Leaking: UNKNOWN
    │    Retaining 2317608 bytes in 31787 objects
    │    ↓ AdSessionContext.webView
    │                       ~~~~~~~
    ├─ com.mopub.mobileads.HtmlWebView instance
    │    Leaking: UNKNOWN
    │    Retaining 2317508 bytes in 31784 objects
    │    View not part of a window view hierarchy
    │    View.mAttachInfo is null (view detached)
    │    View.mWindowAttachCount = 0
    │    mContext instance of com.myapp.MainApplication
    │    ↓ HtmlWebView.mProvider
    │                  ~~~~~~~~~
    ├─ com.android.webview.chromium.WebViewChromium instance
    │    Leaking: UNKNOWN
    │    Retaining 2315220 bytes in 31746 objects
    │    u instance of sB, wrapping com.myapp.MainApplication
    │    ↓ WebViewChromium.A
    │                      ~
    ├─ K7 instance
    │    Leaking: UNKNOWN
    │    Retaining 32 bytes in 1 objects
    │    ↓ K7.e
    │         ~
    ├─ com.mopub.mobileads.HtmlWebViewClient instance
    │    Leaking: UNKNOWN
    │    Retaining 2308595 bytes in 31579 objects
    │    mContext instance of com.myapp.MainApplication
    │    ↓ HtmlWebViewClient.mBaseWebViewListener
    │                        ~~~~~~~~~~~~~~~~~~~~
    ├─ com.mopub.mobileads.HtmlController$HtmlWebViewListener instance
    │    Leaking: UNKNOWN
    │    Retaining 2308543 bytes in 31577 objects
    │    ↓ HtmlController$HtmlWebViewListener.this$0
    │                                         ~~~~~~
    ├─ com.mopub.mobileads.HtmlController instance
    │    Leaking: UNKNOWN
    │    Retaining 2308531 bytes in 31576 objects
    │    mContext instance of com.myapp.MainApplication
    │    ↓ HtmlController.mBaseWebViewListener
    │                     ~~~~~~~~~~~~~~~~~~~~
    ├─ com.mopub.mobileads.MoPubFullscreen$MoPubFullScreenWebListener instance
    │    Leaking: UNKNOWN
    │    Retaining 2307586 bytes in 31566 objects
    │    ↓ MoPubFullscreen$MoPubFullScreenWebListener.this$0
    │                                                 ~~~~~~
    ├─ com.mopub.mobileads.MoPubFullscreen instance
    │    Leaking: UNKNOWN
    │    Retaining 2303601 bytes in 31554 objects
    │    mContext instance of com.myapp.view.main.MainActivity with mDestroyed = true
    │    ↓ MoPubFullscreen.mContext
    │                      ~~~~~~~~
    ╰→ com.myapp.view.main.MainActivity instance
    ​     Leaking: YES (ObjectWatcher was watching this because com.myapp.view.main.MainActivity received
    ​     Activity#onDestroy() callback and Activity#mDestroyed is true)
    ​     Retaining 2303371 bytes in 31548 objects
    ​     key = c3b5ca61-4043-4925-94c8-efec31041a6f
    ​     watchDurationMillis = 5245
    ​     retainedDurationMillis = 237
    ​     mApplication instance of com.myapp.MainApplication
    ​     mBase instance of androidx.appcompat.view.ContextThemeWrapper, not wrapping known Android context
    ====================================
    0 LIBRARY LEAKS


**Sample Project leak:**
    ====================================
    HEAP ANALYSIS RESULT
    ====================================
    1 APPLICATION LEAKS
    
    References underlined with "~~~" are likely causes.
    Learn more at https://squ.re/leaks.
    
    304750 bytes retained by leaking objects
    Signature: 10abd240c4d493a8359d1aba6446b0929d72581
    ┬───
    │ GC Root: Input or output parameters in native code
    │
    ├─ android.os.MessageQueue instance
    │    Leaking: NO (MessageQueue#mQuitting is false)
    │    HandlerThread: "main"
    │    ↓ MessageQueue.mMessages
    │                   ~~~~~~~~~
    ├─ android.os.Message instance
    │    Leaking: UNKNOWN
    │    Retaining 4758 bytes in 70 objects
    │    Message.what = 0
    │    Message.when = 7429128 (90 ms after heap dump)
    │    Message.obj = null
    │    Message.callback = instance @317800528 of com.iab.omid.library.mopub.walking.TreeWalker$3
    │    ↓ Message.next
    │              ~~~~
    ├─ android.os.Message instance
    │    Leaking: UNKNOWN
    │    Retaining 4694 bytes in 69 objects
    │    Message.what = 0
    │    Message.when = 7430121 (1083 ms after heap dump)
    │    Message.obj = null
    │    Message.callback = instance @318077536 of ee
    │    ↓ Message.next
    │              ~~~~
    ├─ android.os.Message instance
    │    Leaking: UNKNOWN
    │    Retaining 4630 bytes in 68 objects
    │    Message.what = 0
    │    Message.when = 21801625 (14372587 ms after heap dump)
    │    Message.obj = null
    │    Message.callback = instance @319651664 of com.mopub.mobileads.-$$Lambda$MoPubFullscreen$3H3zkNFnaPQ4PqCgAa8VbWGmgJs
    │    ↓ Message.callback
    │              ~~~~~~~~
    ├─ com.mopub.mobileads.-$$Lambda$MoPubFullscreen$3H3zkNFnaPQ4PqCgAa8VbWGmgJs instance
    │    Leaking: UNKNOWN
    │    Retaining 4541 bytes in 66 objects
    │    ↓ -$$Lambda$MoPubFullscreen$3H3zkNFnaPQ4PqCgAa8VbWGmgJs.f$0
    │                                                            ~~~
    ├─ com.mopub.mobileads.MoPubFullscreen instance
    │    Leaking: UNKNOWN
    │    Retaining 4529 bytes in 65 objects
    │    mContext instance of com.mopub.simpleadsdemo.MoPubSampleActivity with mDestroyed = true
    │    ↓ MoPubFullscreen.mContext
    │                      ~~~~~~~~
    ╰→ com.mopub.simpleadsdemo.MoPubSampleActivity instance
    ​     Leaking: YES (ObjectWatcher was watching this because com.mopub.simpleadsdemo.MoPubSampleActivity received
    ​     Activity#onDestroy() callback and Activity#mDestroyed is true)
    ​     Retaining 304750 bytes in 4655 objects
    ​     key = 902181f3-f756-4938-a450-1821c146c7b3
    ​     watchDurationMillis = 5237
    ​     retainedDurationMillis = 232
    ​     mApplication instance of androidx.multidex.MultiDexApplication
    ​     mBase instance of android.app.ContextImpl, not wrapping known Android context
    ====================================
    0 LIBRARY LEAKS

**Comment by chauduyphanvu** [comment] 2020-12-04 22:40
@andj207, could you provide us a sample project that reproduces the behavior you are seeing? Thanks!

**Comment by andj207** [comment] 2020-12-07 08:46
@chauduyphanvu use the sample source in this repo and add LeakCanary lib to see the leak.
By the way, I have fixed it in my folk https://github.com/andj207/mopub-android-sdk/commit/d0caf1becc1b77c6dec8b37854a199c48276d3ab

**Comment by chauduyphanvu** [comment] 2020-12-08 16:23
@andj207 - thanks for looking into this. Let me relay the leak and your suggestion to the rest of the team. I'll share an update.

**Comment by chauduyphanvu** [comment] 2021-02-16 22:25
This issue has been fixed in https://github.com/mopub/mopub-android-sdk/releases/tag/v5.16.0. Check it out and let us know if you continue seeing the issue!

**Closed by chauduyphanvu** 2021-02-16 22:25 UTC
Labels: ADF-5600
