### ISSUE TITLE
Crash on AdViewController caused by  Dips.asFloatPixels  (Dips.java:36)

### ISSUE THREAD

**Issue by YanMESS** [mopub/mopub-android-sdk#403] opened 2020-06-30 15:42 UTC
SDK crashes at  Dips.java line 36 (com.mopub.common.util.Dips.asFloatPixels)

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.13.0 (Latest)

#### Android Studio Version:
4.0
#### Gradle Version:
4.0.0
#### Device model and OS Version:
HUAWEI Honor 8C  Android 8.1.0

#### Ad Unit IDs used in reproducing the issue:
Don't know,report from Crashlytics.
#### Steps to reproduce the behavior:
Can't, report from Crashlytics.

#### Expected behavior:
App doesn't crash

#### Observed behavior:
App crashes

#### Evidence:
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference

com.mopub.common.util.Dips.asFloatPixels (Dips.java:36)
com.mopub.common.util.Dips.asIntPixels (Dips.java:41)
com.mopub.mobileads.AdViewController.getAdLayoutParams (AdViewController.java:692)
com.mopub.mobileads.AdViewController.access$100 (AdViewController.java:63)
com.mopub.mobileads.AdViewController$3.run (AdViewController.java:677)
android.os.Handler.handleCallback (Handler.java:809)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:166)
android.app.ActivityThread.main (ActivityThread.java:7555)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:469)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:963)

**Comment by dravyan** [comment] 2020-06-30 23:41
@YanMESS , thank you for reporting. It seems like the Activity or the fragment is null by the time you load AdContentView layout. Can you share more information on steps you carried out before this crash was noticed, complete logs? Is this crash isolated to the specific device only?

Thanks,
MoPub Team

**Comment by YanMESS** [comment] 2020-07-01 00:28
Hi Dravya, 

Thanks for your quick response. 

I think that this bug was introduced on the latest SDK update (v5.13.0). I started seeing it since the update to the latest SDK version. This isn't isolated to specific device as it happens also on other phones for example (CUBOT X19, Galaxy J7 Prime, Galaxy A50, Galaxy S8+,...) but it's a very rare bug as I had 22 crashes (17 users) among thousands of users. I don't know exactly what is the cause but I don't think it has to do with the activity being null (I don't use it on fragments) knowing that it wasn't happening before SDK update. If you don't find a workaround, maybe you can catch it at least to avoid crashing the app. Thanks

Greetings,
Yan

**Comment by dravyan** [comment] 2020-07-02 18:07
@YanMESS, we'll check internally what we can do to prevent the app crash. In the meantime, if you can reproduce the crash locally in your app, please share the app with us for testing purposes.

Thanks,
MoPub Team

**Comment by YanMESS** [comment] 2020-07-03 05:38
Thanks Dravya! 

Unfortunately, I can't reproduce the issue so I can't help on that. I think that maybe it's related to the new FullScreenActivity replacing InterstitialActivity. Maybe it requires changes on Proguard rules or AndroidManifest files? ( I think that you need to change AndroidManifest file on SDK integration guide to follow the addition of FullScreenActivity and remove MoPubActivity and MraidActivity).

Best regards,
Yan

**Comment by dravyan** [comment] 2020-07-08 16:39
@YanMESS, We do not need `MoPubActivity` and `MraidActivity` in AndroidManifest if you are on MoPub v5.13.0. That will be cleared in the future releases. But that doesn't cause any crash. Regarding the NullPointerException reported above, our team will investigate. We will update the thread once we have more information to share. Thank you!

- MoPub Team

**Comment by GlebMaltsev** [comment] 2020-07-20 12:13
We're facing with the same issue (stacktrace and error message is identical). We have similar crash rate (~1-2%), and it seems that issue completely not related to OS version or vendor. We're using MoPub v5.13.1.

Our crashes are also has been started after bumping up MoPub SDK version (from 5.12.0 to 5.13.1). No any other changes was made. Here some notes I figured out during invetisgating crash logs:

- Crashes appeares only on the screens with banner ads;
- Crashes appeares when user go out from that screen (in few moments after **Fragment.onStop()** and **Fragment.onDestroyView()** callback has been fired). We're sure that client app correctly call **MoPubView.destroy()** inside **Fragment.onDestroyView()** callback.
- Small crash rate could signal that crash occur due bad results in some race condition.
- According to the stacktrace, issue occur during executing **run()** block inside **AdViewController.setAdContentView()** method.



Unfortunatly, I was no able to reproduce the crash. However I have a guess about what could be wrong. 

1. **AdViewController.setAdContentView()** is called. **MoPubView** is still attached to the UI, everything is working as expected, and **if (moPubAd instanceof MoPubView)** gives **true** and you post your runnable in the end of UI queue. 
2. However there are UI destroying messages already in that queue (for example user clicked "back button" and client is closing Fragment with Banner ads). If those messages contains **MoPubView.destroy()** call, it means that at the moment of executing **run()** block inside **AdViewController.setAdContentView()** method, **AdViewController.cleanup()** was finished which set **AdViewController.mContext** field to **null**.
3. **run()** block inside **AdViewController.setAdContentView()** doesn't check state of **AdViewController.mContext** field and start to use it inside **AdViewController.getAdLayoutParams()** which leads to NPE.

**Comment by GlebMaltsev** [comment] 2020-07-20 14:37
Update to the my comment above: what I wrote above is true for version 5.13.1. If we will open **AdViewController.setAdContentView()** method from version 5.12.0 (which has no this crash), we will see that it contains the following check inside **run** block:

```
if (moPubView == null) {
      return;
}
```

as result, crash not occur because in crash-like scenario that **if** statement returns **true** and method do nothing.

**Comment by GlebMaltsev** [comment] 2020-09-29 12:57
Any ETA about when this one-line issue will be fixed?

**Comment by chauduyphanvu** [comment] 2020-09-29 13:30
@GlebMaltsev, it's addressed internally, and the fix will be deployed with the upcoming SDK version. Stay tuned!

**Comment by YanMESS** [comment] 2020-09-29 16:08
> @GlebMaltsev, it's addressed internally, and the fix will be deployed with the upcoming SDK version. Stay tuned!

Do you know when the fix will be released? I received an announcement email saying that V 5.14.0 will be released on or about September 28th.

Thanks!

**Comment by chauduyphanvu** [comment] 2020-10-01 19:41
@YanMESS, v5.14.0 is available now! Update and let us know if you continue seeing the issue.

**Closed by chauduyphanvu** 2020-10-01 19:41 UTC
Labels: ADF-5182

**Comment by YanMESS** [comment] 2020-10-01 19:49
Thanks! I will.
